<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Menu · Kuligo Resto</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/customer.css') }}">
</head>
<body class="customer-body" data-checkout="{{ route('menu.checkout', $meja->kode_qr) }}" data-payment="{{ route('menu.bayar', $meja->kode_qr) }}" data-status="{{ route('menu.status', [$meja->kode_qr, '__ORDER__']) }}">
<header class="customer-header"><a class="customer-brand" href="#"><span class="brand-mark">k</span><span>kuligo<small>RESTO</small></span></a><div class="table-indicator"><span class="live-dot"></span> Meja {{ $meja->nomor_meja }}</div><button class="cart-trigger" type="button" onclick="document.querySelector('#cart').scrollIntoView({behavior:'smooth'})"><span>Keranjang</span><b id="header-count">0</b></button></header>
<main class="customer-main">
    <section class="welcome-row"><div><span class="eyebrow">SELAMAT DATANG DI KULIGO</span><h1>Temukan menu<br><em>favoritmu.</em></h1><p>Hidangan hangat dan minuman segar, dibuat dengan sepenuh hati.</p></div><div class="welcome-art" aria-hidden="true"><span>✦</span><div class="art-plate">🥘</div><i>BAIK · SEGAR · LEZAT</i></div></section>
    <section class="promo-banner"><div><span class="promo-kicker">KHUSUS HARI INI</span><h2>Waktunya makan enak.</h2><p>Pilih menu favoritmu, kami siapkan untukmu.</p></div><span class="promo-spark">✳</span></section>
    <div class="catalog-layout"><section class="catalog"><div class="catalog-head"><div><span class="eyebrow">DARI DAPUR KAMI</span><h2>Jelajahi menu</h2></div><label class="search-field"><span>⌕</span><input id="menu-search" type="search" placeholder="Cari menu..." aria-label="Cari menu"></label></div>
        <nav class="category-tabs" aria-label="Kategori menu"><button class="category-tab active" data-category="all">Semua menu</button>@foreach($kategori as $item)<button class="category-tab" data-category="{{ $item->id_kategori }}">{{ $item->nama_kategori }}</button>@endforeach</nav>
        @forelse($kategori as $group)
            @if($group->menu->isNotEmpty())<section class="menu-group" data-group="{{ $group->id_kategori }}"><div class="group-heading"><h3>{{ $group->nama_kategori }}</h3><span>{{ $group->menu->count() }} pilihan</span></div><div class="menu-grid">
                @foreach($group->menu as $item)<article class="menu-card" data-name="{{ strtolower($item->nama_menu.' '.$item->deskripsi) }}" data-category="{{ $group->id_kategori }}" data-id="{{ $item->id_menu }}" data-title="{{ $item->nama_menu }}" data-price="{{ $item->harga_dasar }}" data-image="{{ $item->url_gambar }}" data-variants="{{ $item->varian->map(fn($v) => ['id' => $v->id_varian, 'name' => $v->nama_varian, 'price' => $v->harga_tambahan])->toJson() }}">
                    <div class="food-image">@if($item->url_gambar)<img src="{{ $item->url_gambar }}" alt="{{ $item->nama_menu }}" loading="lazy">@else<span>{{ str_contains(strtolower($group->nama_kategori), 'minum') ? '🥤' : '🍽️' }}</span>@endif</div>
                    <div class="menu-card-copy"><div class="menu-title-line"><h4>{{ $item->nama_menu }}</h4><button class="add-button" type="button" aria-label="Tambah {{ $item->nama_menu }}">+</button></div><p>{{ $item->deskripsi ?: 'Disiapkan segar oleh dapur Kuligo.' }}</p><strong>Rp {{ number_format($item->harga_dasar, 0, ',', '.') }}</strong></div>
                </article>@endforeach
            </div></section>@endif
        @empty <div class="empty-menu"><span>🍽️</span><h3>Menu sedang disiapkan</h3><p>Silakan kembali sebentar lagi.</p></div> @endforelse
        @if($kategori->every(fn($group) => $group->menu->isEmpty()))<div class="empty-menu"><span>🍽️</span><h3>Menu sedang disiapkan</h3><p>Silakan kembali sebentar lagi.</p></div>@endif
    </section>
    <aside class="cart-panel" id="cart"><div class="cart-title"><div><span class="eyebrow">PESANANMU</span><h2>Keranjang</h2></div><span class="cart-count" id="cart-count">0 item</span></div><div class="cart-items" id="cart-items"><div class="cart-empty"><span>🧺</span><p>Keranjangmu masih kosong.<br>Yuk, pilih menu favorit!</p></div></div><div class="cart-summary"><div><span>Subtotal</span><b id="cart-subtotal">Rp 0</b></div><small>Harga sudah termasuk pajak.</small><button id="checkout-button" class="checkout-button" type="button" disabled>Lanjut ke pembayaran <span>→</span></button><p class="secure-note">Pembayaran diverifikasi oleh kasir</p></div></aside></div>
</main>
<footer class="customer-footer"><span>kuligo <b>RESTO</b></span><span>Terima kasih telah memilih kami · Meja {{ $meja->nomor_meja }}</span></footer>
<dialog id="checkout-dialog" class="checkout-dialog"><form method="dialog" class="dialog-close"><button aria-label="Tutup">×</button></form><div id="checkout-step"><span class="eyebrow">SATU LANGKAH LAGI</span><h2>Konfirmasi pesanan</h2><p class="dialog-intro">Periksa pesananmu dan pilih cara pembayaran.</p><label class="form-label">Nama pemesan <span>(opsional)</span><input id="customer-name" maxlength="100" placeholder="Nama kamu"></label><div class="payment-label">Metode pembayaran</div><div class="payment-options"><label class="payment-option"><input type="radio" name="payment-method" value="qris" checked><span class="payment-icon">▦</span><span><b>QRIS</b><small>Scan dengan aplikasi pembayaran</small></span><i>✓</i></label><label class="payment-option"><input type="radio" name="payment-method" value="e_wallet"><span class="payment-icon">◉</span><span><b>E-wallet</b><small>Dompet digital pilihanmu</small></span><i>✓</i></label><label class="payment-option"><input type="radio" name="payment-method" value="kartu_debit"><span class="payment-icon">▰</span><span><b>Kartu debit</b><small>Bayar dengan kartu debit</small></span><i>✓</i></label></div><div class="dialog-total"><span>Total pembayaran</span><b id="dialog-total">Rp 0</b></div><button class="checkout-button" id="place-order" type="button">Buat pesanan <span>→</span></button><p id="checkout-error" class="checkout-error" role="alert"></p></div><div id="success-step" class="success-step" hidden><span class="success-mark">✓</span><span class="eyebrow">PESANAN DITERIMA</span><h2>Terima kasih!<br>Pesanan sedang disiapkan.</h2><p>Kasir akan memverifikasi pembayaranmu. Tunjukkan nomor pesanan ini jika diperlukan.</p><div class="order-number"><span>Nomor pesanan</span><b id="success-order"></b></div><a class="checkout-button" id="track-order" href="#">Lihat status pesanan <span>→</span></a></div></dialog>
<script>
(()=>{const body=document.body,cart=new Map(),items=document.querySelector('#cart-items'),money=n=>'Rp '+new Intl.NumberFormat('id-ID').format(n),cards=[...document.querySelectorAll('.menu-card')];let activeCategory='all';
function render(){let count=0,total=0;items.innerHTML='';if(!cart.size){items.innerHTML='<div class="cart-empty"><span>🧺</span><p>Keranjangmu masih kosong.<br>Yuk, pilih menu favorit!</p></div>'}for(const [key,line] of cart){const quantity=line.quantity,price=Number(line.price),sum=price*quantity;count+=quantity;total+=sum;const row=document.createElement('div');row.className='cart-line';row.innerHTML=`<div class="cart-line-copy"><b>${line.title}</b><small>${line.variantName||'Reguler'} · ${money(sum)}</small></div><div class="quantity-control"><button type="button" data-action="minus" data-key="${key}" aria-label="Kurangi">−</button><b>${quantity}</b><button type="button" data-action="plus" data-key="${key}" aria-label="Tambah">+</button></div>`;items.append(row)}document.querySelector('#cart-count').textContent=`${count} item`;document.querySelector('#header-count').textContent=count;document.querySelector('#cart-subtotal').textContent=money(total);document.querySelector('#dialog-total').textContent=money(total);document.querySelector('#checkout-button').disabled=!count}
function add(card,variant=null){const variants=JSON.parse(card.dataset.variants||'[]'),id=variant?.id||variants[0]?.id||'',name=variant?.name||variants[0]?.name||'',price=Number(card.dataset.price)+(Number(variant?.price??variants[0]?.price)||0),key=`${card.dataset.id}-${id}`;if(cart.has(key))cart.get(key).quantity++;else cart.set(key,{id:card.dataset.id,title:card.dataset.title,price,variant:id||null,variantName:name,quantity:1});render()}
cards.forEach(card=>{card.querySelector('.add-button').addEventListener('click',()=>{const variants=JSON.parse(card.dataset.variants||'[]');if(variants.length>1){const selection=prompt('Pilih varian:\n'+variants.map((v,i)=>`${i+1}. ${v.name}${Number(v.price)?' (+ '+money(v.price)+')':''}`).join('\n'));const option=variants[Number(selection)-1];if(!option)return;add(card,option)}else add(card,variants[0]||null)})});items.addEventListener('click',event=>{const button=event.target.closest('button[data-action]');if(!button)return;const line=cart.get(button.dataset.key);if(button.dataset.action==='plus')line.quantity++;else line.quantity--;if(line.quantity<1)cart.delete(button.dataset.key);render()});
function filter(){const query=document.querySelector('#menu-search').value.trim().toLocaleLowerCase('id');cards.forEach(card=>card.hidden=!(activeCategory==='all'||card.dataset.category===activeCategory)||!card.dataset.name.includes(query));document.querySelectorAll('.menu-group').forEach(group=>group.hidden=!group.querySelector('.menu-card:not([hidden])'))}document.querySelector('#menu-search').addEventListener('input',filter);document.querySelectorAll('.category-tab').forEach(tab=>tab.addEventListener('click',()=>{activeCategory=tab.dataset.category;document.querySelectorAll('.category-tab').forEach(other=>other.classList.toggle('active',other===tab));filter()}));
const dialog=document.querySelector('#checkout-dialog');document.querySelector('#checkout-button').addEventListener('click',()=>dialog.showModal());document.querySelector('#place-order').addEventListener('click',async event=>{const button=event.currentTarget,error=document.querySelector('#checkout-error');button.disabled=true;button.innerHTML='Memproses…';error.textContent='';try{const checkout=await fetch(body.dataset.checkout,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({nama_pelanggan:document.querySelector('#customer-name').value,items:[...cart.values()].map(line=>({id_menu:line.id,id_varian:line.variant,jumlah:line.quantity}))})});const order=await checkout.json();if(!checkout.ok)throw new Error(Object.values(order.errors||{}).flat()[0]||order.message||'Pesanan belum dapat diproses.');const payment=await fetch(body.dataset.payment,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({no_pesanan:order.no_pesanan,metode_pembayaran:document.querySelector('[name="payment-method"]:checked').value})});const result=await payment.json();if(!payment.ok)throw new Error(result.message||'Pembayaran belum dapat diproses.');document.querySelector('#checkout-step').hidden=true;document.querySelector('#success-step').hidden=false;document.querySelector('#success-order').textContent=order.no_pesanan;document.querySelector('#track-order').href=body.dataset.status.replace('__ORDER__',encodeURIComponent(order.no_pesanan));cart.clear();render()}catch(exception){error.textContent=exception.message;button.disabled=false;button.innerHTML='Coba lagi <span>→</span>'}});render()})();
</script>
</body></html>
