@extends('layouts.cashier')
@section('title', 'Pesanan Kasir')
@section('content')
<div class="breadcrumb">KULIGO POS / <b>DAFTAR PESANAN</b></div>
<div class="page-heading cashier-heading"><div><span class="cashier-kicker">ANTREAN LANGSUNG</span><h1>Tampilan Pesanan</h1><p>Kelola pesanan masuk, proses di dapur, dan antar ke meja pelanggan.</p></div><span class="cashier-date"><i class="queue-live-dot"></i> {{ now()->translatedFormat('l, d M Y') }}</span></div>
<div class="board-toolbar"><div class="board-filters"><a class="board-filter active" href="#masuk">Semua <b>{{ $pesananBaru->count() + $pesananDiproses->count() + $pesananSiap->count() }}</b></a><a class="board-filter" href="#masuk">Masuk <b>{{ $pesananBaru->count() }}</b></a><a class="board-filter" href="#diproses">Diproses <b>{{ $pesananDiproses->count() }}</b></a><a class="board-filter" href="#siap-diantar">Siap diantar <b>{{ $pesananSiap->count() }}</b></a></div><a href="{{ route('kasir.dashboard') }}" class="button button-light">Ringkasan dashboard</a></div>

<div class="order-board">
    <section class="board-column" id="masuk"><header class="board-column-head"><span class="board-dot incoming"></span><div><h2>Pesanan Masuk</h2><small>Perlu verifikasi kasir</small></div><b class="board-total">{{ $pesananBaru->count() }}</b></header><div class="board-cards">
    @forelse($pesananBaru as $order)<article class="board-card"><div class="board-card-top"><b>#{{ $order->no_pesanan }}</b><time>{{ $order->waktu_pesan?->format('H:i') }}</time></div><div class="board-card-meta"><span>MEJA {{ $order->meja->nomor_meja }}</span><span>{{ $order->nama_pelanggan ?: 'Pelanggan' }}</span></div><div class="board-card-items">@foreach($order->detail->take(3) as $detail)<div><span>{{ $detail->jumlah }}× {{ $detail->menu->nama_menu }}</span><b>Rp {{ number_format($detail->subtotal, 0, ',', '.') }}</b></div>@endforeach @if($order->detail->count() > 3)<small>+ {{ $order->detail->count() - 3 }} item lainnya</small>@endif</div><div class="board-card-total"><span>Total</span><b>Rp {{ number_format($order->total_harga, 0, ',', '.') }}</b></div><div class="board-card-payment"><span>{{ $order->pembayaran?->metode_pembayaran ? strtoupper(str_replace('_', ' ', $order->pembayaran->metode_pembayaran)) : 'BELUM DIBAYAR' }}</span><b>{{ ucfirst($order->pembayaran?->status_pembayaran ?? 'pending') }}</b></div><div class="board-card-actions"><a href="{{ route('kasir.pesanan.show', $order) }}">{{ $order->pembayaran?->metode_pembayaran === 'tunai' ? 'Input kembalian' : 'Detail' }}</a>@if($order->pembayaran?->metode_pembayaran !== 'tunai')<form method="POST" action="{{ route('kasir.pesanan.verifikasi', $order) }}">@csrf<input type="hidden" name="valid" value="1"><button type="submit">Verifikasi &amp; proses</button></form>@endif</div></article>@empty<div class="board-empty">Belum ada pesanan masuk.</div>@endforelse
    </div></section>

    <section class="board-column" id="diproses"><header class="board-column-head"><span class="board-dot cooking"></span><div><h2>Diproses</h2><small>Sedang disiapkan dapur</small></div><b class="board-total">{{ $pesananDiproses->count() }}</b></header><div class="board-cards">
    @forelse($pesananDiproses as $order)<article class="board-card"><div class="board-card-top"><b>#{{ $order->no_pesanan }}</b><time>{{ $order->waktu_pesan?->format('H:i') }}</time></div><div class="board-card-meta"><span>MEJA {{ $order->meja->nomor_meja }}</span><span>{{ $order->nama_pelanggan ?: 'Pelanggan' }}</span></div><div class="board-card-items">@foreach($order->detail->take(3) as $detail)<div><span>{{ $detail->jumlah }}× {{ $detail->menu->nama_menu }}</span><b>Rp {{ number_format($detail->subtotal, 0, ',', '.') }}</b></div>@endforeach @if($order->detail->count() > 3)<small>+ {{ $order->detail->count() - 3 }} item lainnya</small>@endif</div><div class="board-card-total"><span>Total pesanan</span><b>Rp {{ number_format($order->total_harga, 0, ',', '.') }}</b></div><div class="board-card-actions"><a href="{{ route('kasir.pesanan.show', $order) }}">Detail</a><form method="POST" action="{{ route('kasir.pesanan.status', $order) }}">@csrf<input type="hidden" name="status" value="siap_diantar"><button type="submit">Tandai siap diantar ✓</button></form></div></article>@empty<div class="board-empty">Belum ada pesanan diproses.</div>@endforelse
    </div></section>

    <section class="board-column" id="siap-diantar"><header class="board-column-head"><span class="board-dot ready"></span><div><h2>Siap Diantar</h2><small>Antarkan ke meja pelanggan</small></div><b class="board-total">{{ $pesananSiap->count() }}</b></header><div class="board-cards">
    @forelse($pesananSiap as $order)<article class="board-card"><div class="board-card-top"><b>#{{ $order->no_pesanan }}</b><time>{{ $order->waktu_pesan?->format('H:i') }}</time></div><div class="board-card-meta"><span>MEJA {{ $order->meja->nomor_meja }}</span><span>{{ $order->nama_pelanggan ?: 'Pelanggan' }}</span></div><div class="board-card-items">@foreach($order->detail->take(3) as $detail)<div><span>{{ $detail->jumlah }}× {{ $detail->menu->nama_menu }}</span><b>Rp {{ number_format($detail->subtotal, 0, ',', '.') }}</b></div>@endforeach @if($order->detail->count() > 3)<small>+ {{ $order->detail->count() - 3 }} item lainnya</small>@endif</div><div class="board-card-total"><span>Total pesanan</span><b>Rp {{ number_format($order->total_harga, 0, ',', '.') }}</b></div><div class="board-card-actions"><a href="{{ route('kasir.pesanan.show', $order) }}">Detail</a><form method="POST" action="{{ route('kasir.pesanan.status', $order) }}">@csrf<input type="hidden" name="status" value="selesai"><button class="finish-button" type="submit">Selesaikan ✓</button></form></div></article>@empty<div class="board-empty">Belum ada pesanan siap diantar.</div>@endforelse
    </div></section>
</div>
<div class="board-note"><span class="online-dot"></span> Status pesanan menggunakan data terbaru dari transaksi pelanggan <a href="{{ route('kasir.dashboard') }}">Kembali ke dashboard →</a></div>
@endsection
